<?php
require_once 'config.php'; require_once 'helpers.php';
function catUsuario($c,$id,$u){$st=$c->prepare("SELECT cat.* FROM categorias cat JOIN criancas cr ON cr.id_crianca=cat.crianca_id WHERE cat.id_categoria=? AND cr.usuario_id=?");$st->bind_param("ii",$id,$u);$st->execute();$r=$st->get_result();if(!$r->num_rows)erro('Categoria não encontrada',403);return$r->fetch_assoc();}
$m=$_SERVER['REQUEST_METHOD'];
if($m==='GET'){if(empty($_GET['crianca_id']))erro('crianca_id é obrigatório');if(!empty($_GET['device_secret']))$cr=exigirDispositivoPareado($conn,$_GET['device_secret']);else{$u=exigirSessao($conn,$_GET['token']??'');$cr=exigirCriancaDoUsuario($conn,(int)$_GET['crianca_id'],$u['id_usuario']);}$id=(int)$cr['id_crianca'];$r=$conn->query("SELECT id_categoria,nome_categoria,emoji,cor,ordem FROM categorias WHERE crianca_id=$id ORDER BY ordem,id_categoria");$a=[];while($x=$r->fetch_assoc())$a[]=$x;responder(['success'=>true,'categorias'=>$a]);}
$d=corpoJson();$u=exigirSessao($conn,$d['token']??'');$uid=$u['id_usuario'];
if($m==='POST'){if(empty($d['crianca_id'])||empty($d['nome_categoria']))erro('crianca_id e nome_categoria são obrigatórios');exigirCriancaDoUsuario($conn,$d['crianca_id'],$uid);$o=$conn->query("SELECT COALESCE(MAX(ordem),0)+1 n FROM categorias WHERE crianca_id=".(int)$d['crianca_id'])->fetch_assoc()['n'];$st=$conn->prepare("INSERT INTO categorias (crianca_id,nome_categoria,emoji,cor,ordem) VALUES (?,?,?,?,?)");$e=$d['emoji']??'📋';$cor=$d['cor']??'#BDE0FE';$st->bind_param("isssi",$d['crianca_id'],$d['nome_categoria'],$e,$cor,$o);$st->execute();responder(['success'=>true,'id_categoria'=>$conn->insert_id]);}
if(empty($d['id_categoria']))erro('id_categoria é obrigatório');catUsuario($conn,$d['id_categoria'],$uid);$id=(int)$d['id_categoria'];
if($m==='DELETE'){$conn->query("DELETE FROM categorias WHERE id_categoria=$id");responder(['success'=>true]);}
if($m==='PUT'){ $set=[];$vals=[];$types='';foreach(['nome_categoria','emoji','cor'] as $k)if(isset($d[$k])){$set[]="$k=?";$vals[]=$d[$k];$types.='s';}if(isset($d['ordem'])){$set[]='ordem=?';$vals[]=(int)$d['ordem'];$types.='i';}if(!$set)erro('Nenhum campo para atualizar');$vals[]=$id;$types.='i';$st=$conn->prepare("UPDATE categorias SET ".implode(',',$set)." WHERE id_categoria=?");$st->bind_param($types,...$vals);$st->execute();responder(['success'=>true]);}
erro('Método não permitido',405);
