<?php
require_once 'config.php'; require_once 'helpers.php';
function falaUsuario($c,$id,$u){$st=$c->prepare("SELECT f.* FROM falas f JOIN categorias cat ON cat.id_categoria=f.id_categoria JOIN criancas cr ON cr.id_crianca=cat.crianca_id WHERE f.id_fala=? AND cr.usuario_id=?");$st->bind_param("ii",$id,$u);$st->execute();$r=$st->get_result();if(!$r->num_rows)erro('Pictograma não encontrado',403);return$r->fetch_assoc();}
$m=$_SERVER['REQUEST_METHOD'];
if($m==='GET'){if(empty($_GET['id_categoria']))erro('id_categoria é obrigatório');$id=(int)$_GET['id_categoria'];if(!empty($_GET['device_secret']))exigirDispositivoPareado($conn,$_GET['device_secret']);else{$u=exigirSessao($conn,$_GET['token']??'');$st=$conn->prepare("SELECT cat.id_categoria FROM categorias cat JOIN criancas cr ON cr.id_crianca=cat.crianca_id WHERE cat.id_categoria=? AND cr.usuario_id=?");$st->bind_param("ii",$id,$u['id_usuario']);$st->execute();if(!$st->get_result()->num_rows)erro('Categoria não encontrada',403);}$r=$conn->query("SELECT id_fala,texto,emoji,imagem_url,ordem FROM falas WHERE id_categoria=$id ORDER BY ordem,id_fala");$a=[];while($x=$r->fetch_assoc())$a[]=$x;responder(['success'=>true,'falas'=>$a]);}
$d=corpoJson();$u=exigirSessao($conn,$d['token']??'');$uid=$u['id_usuario'];
if($m==='POST'){if(empty($d['id_categoria'])||empty($d['texto']))erro('id_categoria e texto são obrigatórios');$st=$conn->prepare("SELECT cat.id_categoria FROM categorias cat JOIN criancas cr ON cr.id_crianca=cat.crianca_id WHERE cat.id_categoria=? AND cr.usuario_id=?");$st->bind_param("ii",$d['id_categoria'],$uid);$st->execute();if(!$st->get_result()->num_rows)erro('Categoria não encontrada',403);$emoji=$d['emoji']??'💬';$img=$d['imagem_url']??null;$ord=$conn->query("SELECT COALESCE(MAX(ordem),0)+1 n FROM falas WHERE id_categoria=".(int)$d['id_categoria'])->fetch_assoc()['n'];$st=$conn->prepare("INSERT INTO falas (id_categoria,texto,emoji,imagem_url,ordem) VALUES (?,?,?,?,?)");$st->bind_param("isssi",$d['id_categoria'],$d['texto'],$emoji,$img,$ord);$st->execute();responder(['success'=>true,'id_fala'=>$conn->insert_id]);}
if(empty($d['id_fala']))erro('id_fala é obrigatório');falaUsuario($conn,$d['id_fala'],$uid);$id=(int)$d['id_fala'];
if($m==='DELETE'){$conn->query("DELETE FROM falas WHERE id_fala=$id");responder(['success'=>true]);}
if($m==='PUT'){$set=[];$vals=[];$types='';foreach(['texto','emoji','imagem_url'] as $k)if(array_key_exists($k,$d)){$set[]="$k=?";$vals[]=$d[$k];$types.='s';}if(isset($d['ordem'])){$set[]='ordem=?';$vals[]=(int)$d['ordem'];$types.='i';}$vals[]=$id;$types.='i';if(!$set)erro('Nenhum campo para atualizar');$st=$conn->prepare("UPDATE falas SET ".implode(',',$set)." WHERE id_fala=?");$st->bind_param($types,...$vals);$st->execute();responder(['success'=>true]);}
erro('Método não permitido',405);
