<?php
require_once 'config.php'; require_once 'helpers.php';
$m=$_SERVER['REQUEST_METHOD'];
if($m==='GET'){$u=exigirSessao($conn,$_GET['token']??'');if(empty($_GET['crianca_id']))erro('crianca_id é obrigatório');exigirCriancaDoUsuario($conn,(int)$_GET['crianca_id'],$u['id_usuario']);$id=(int)$_GET['crianca_id'];$r=$conn->query("SELECT codigo,expira_em FROM pareamento_codigos WHERE crianca_id=$id AND expira_em>NOW() AND usado=0 ORDER BY criado_em DESC LIMIT 1");responder(['success'=>true,'codigo_ativo'=>$r&&$r->num_rows?$r->fetch_assoc():null]);}
$d=corpoJson();$acao=$d['acao']??'';
if($acao==='gerar'){$u=exigirSessao($conn,$d['token']??'');if(empty($d['crianca_id']))erro('crianca_id é obrigatório');exigirCriancaDoUsuario($conn,(int)$d['crianca_id'],$u['id_usuario']);$c=gerarCodigoPareamento();$st=$conn->prepare("INSERT INTO pareamento_codigos (crianca_id,codigo,expira_em,usado) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 30 DAY),0)");$st->bind_param("is",$d['crianca_id'],$c);$st->execute();responder(['success'=>true,'codigo'=>$c,'validade_dias'=>30]);}
if($acao==='validar'){if(empty($d['codigo']))erro('Código é obrigatório');$st=$conn->prepare("SELECT crianca_id FROM pareamento_codigos WHERE codigo=? AND expira_em>NOW() AND usado=0 ORDER BY criado_em DESC LIMIT 1");$st->bind_param("s",$d['codigo']);$st->execute();$r=$st->get_result();if(!$r->num_rows)erro('Código inválido ou expirado',404);$id=(int)$r->fetch_assoc()['crianca_id'];$st=$conn->prepare("UPDATE pareamento_codigos SET usado=1 WHERE codigo=?");$st->bind_param("s",$d['codigo']);$st->execute();$sec=gerarDeviceSecret();$st=$conn->prepare("INSERT INTO dispositivos_crianca (crianca_id,device_secret) VALUES (?,?)");$st->bind_param("is",$id,$sec);$st->execute();$cr=$conn->query("SELECT * FROM criancas WHERE id_crianca=$id")->fetch_assoc();responder(['success'=>true,'device_secret'=>$sec,'crianca'=>formatarCrianca($cr)]);}
if($acao==='verificar_dispositivo'){if(empty($d['device_secret']))erro('device_secret é obrigatório');$cr=exigirDispositivoPareado($conn,$d['device_secret']);responder(['success'=>true,'crianca'=>formatarCrianca($cr)]);}
erro('Ação inválida');
