<?php
require_once 'config.php'; require_once 'helpers.php';
function rotinaUsuario($c,$id,$u){$st=$c->prepare("SELECT r.* FROM rotinas r JOIN criancas cr ON cr.id_crianca=r.crianca_id WHERE r.id_rotina=? AND cr.usuario_id=?");$st->bind_param("ii",$id,$u);$st->execute();$r=$st->get_result();if(!$r->num_rows)erro('Rotina não encontrada',403);return$r->fetch_assoc();}
$m=$_SERVER['REQUEST_METHOD'];
if($m==='GET'){if(empty($_GET['crianca_id']))erro('crianca_id é obrigatório');if(!empty($_GET['device_secret']))$cr=exigirDispositivoPareado($conn,$_GET['device_secret']);else{$u=exigirSessao($conn,$_GET['token']??'');$cr=exigirCriancaDoUsuario($conn,(int)$_GET['crianca_id'],$u['id_usuario']);}$id=(int)$cr['id_crianca'];$sql="SELECT id_rotina,atividade,horario,dia_semana,icone FROM rotinas WHERE crianca_id=$id";if(!empty($_GET['dia_semana']))$sql.=" AND FIND_IN_SET('".$conn->real_escape_string($_GET['dia_semana'])."',dia_semana)>0";$sql.=" ORDER BY horario";$r=$conn->query($sql);$a=[];$hoje=date('Y-m-d');while($x=$r->fetch_assoc()){$x['dias_semana']=$x['dia_semana']?explode(',',$x['dia_semana']):[];$q=$conn->query("SELECT 1 FROM rotina_execucoes WHERE rotina_id=".(int)$x['id_rotina']." AND data_execucao='$hoje'");$x['concluida_hoje']=$q&&$q->num_rows>0;$a[]=$x;}responder(['success'=>true,'rotinas'=>$a]);}
$d=corpoJson();$acao=$d['acao']??'criar';
if($m==='POST'&&$acao==='concluir'){if(empty($d['id_rotina']))erro('id_rotina é obrigatório');if(!empty($d['device_secret']))exigirDispositivoPareado($conn,$d['device_secret']);else{$u=exigirSessao($conn,$d['token']??'');rotinaUsuario($conn,(int)$d['id_rotina'],$u['id_usuario']);}$id=(int)$d['id_rotina'];$dt=$d['data']??date('Y-m-d');$st=$conn->prepare("INSERT IGNORE INTO rotina_execucoes (rotina_id,data_execucao) VALUES (?,?)");$st->bind_param("is",$id,$dt);$st->execute();responder(['success'=>true,'message'=>'Rotina concluída']);}
$u=exigirSessao($conn,$d['token']??'');$uid=$u['id_usuario'];
if($m==='POST'){if(empty($d['crianca_id'])||empty($d['atividade'])||empty($d['horario']))erro('crianca_id, atividade e horario são obrigatórios');exigirCriancaDoUsuario($conn,(int)$d['crianca_id'],$uid);$dias=is_array($d['dias_semana']??null)?implode(',',$d['dias_semana']):'';$icone=$d['icone']??'⭐';$st=$conn->prepare("INSERT INTO rotinas (crianca_id,dia_semana,atividade,horario,icone) VALUES (?,?,?,?,?)");$st->bind_param("issss",$d['crianca_id'],$dias,$d['atividade'],$d['horario'],$icone);$st->execute();responder(['success'=>true,'id_rotina'=>$conn->insert_id]);}
if(empty($d['id_rotina']))erro('id_rotina é obrigatório');rotinaUsuario($conn,(int)$d['id_rotina'],$uid);$id=(int)$d['id_rotina'];
if($m==='DELETE'){$conn->query("DELETE FROM rotinas WHERE id_rotina=$id");responder(['success'=>true]);}
if($m==='PUT'){$set=[];$vals=[];$types='';foreach(['atividade','horario','icone'] as $k)if(isset($d[$k])){$set[]="$k=?";$vals[]=$d[$k];$types.='s';}if(isset($d['dias_semana'])){$set[]='dia_semana=?';$vals[]=implode(',',$d['dias_semana']);$types.='s';}$vals[]=$id;$types.='i';if(!$set)erro('Nenhum campo para atualizar');$st=$conn->prepare("UPDATE rotinas SET ".implode(',',$set)." WHERE id_rotina=?");$st->bind_param($types,...$vals);$st->execute();responder(['success'=>true]);}
erro('Método não permitido',405);
